### ISSUE TITLE
Can't paste into search

### ISSUE THREAD

**Issue by yougotwill** [Sn8z/Poddr#36] opened 2018-10-12 16:19 UTC
Hi, so far this app looks amazing! If possible can you make pasting work in the search input I have a Japanese podcast I want to subscribe to and attempting to put the kanji in manually is a nightmare.

Keep up the great work 👏

**Comment by Sn8z** [comment] 2018-10-12 23:39
Thanks! :)
That indeed sounds like a bug, what OS are you on?
It seems to work for me under Linux with both AppImage & snap versions.
Can you paste anything at all or is it just kanji that doesn't work?

**Comment by yougotwill** [comment] 2018-10-13 05:48
I'm on macOS Sierra. You can't right click in the input field to bring up the context menu and the mac paste command (Cmd + V) doesn't work. It's not specific to the kanji.

**Comment by Sn8z** [comment] 2018-10-13 07:07
Ah, I've read about other people with the same issue! Should be a pretty easy fix I think. :)
Will look into it in the upcoming days!

**Comment by Sn8z** [comment] 2018-10-15 13:06
@yougotwill I just pushed an updated Mac version for the 1.0.8 release that should fix the paste problem. It would be awesome if you could download it and confirm that pasting indeed works as intended 💃 
I also realized while fixing this that Poddr today overrides some important OS specific shortcuts, this will be fixed for the next release. For example Quit(Cmd+Q) in Mac wont work atm, these commands do work if selected from the application menu.

**Comment by yougotwill** [comment] 2018-10-18 10:09
It's fixed. Great work 👏 Sorry for the delay, I'm not always close to wifi :) Looking forward to the next update to fix the rest of those shortcuts

**Closed** 2018-10-18 10:09 UTC
Labels: bug

**Comment by Sn8z** [comment] 2018-10-18 10:47
No problems!
I currently only have access to a mid 2010 Macbook Pro which makes testing and building for Mac a bit of a struggle sometimes so feedback and bug reports like this is worth a lot :+1:
